//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRcenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoughtService
    {
        public int BoughtServiceID { get; set; }
        public int ServiceID { get; set; }
        public Nullable<int> UserID { get; set; }
        public int ClientID { get; set; }
        public System.DateTime DateVisit { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Service Service { get; set; }
        public virtual User User { get; set; }
    }
}
