//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRcenter.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SRcenterEntities : DbContext
    {
        public SRcenterEntities()
            : base("name=SRcenterEntities")
        {
        }
        public static SRcenterEntities _context;
        public static SRcenterEntities GetContext()
        {
            if (_context == null)
            {
                _context = new SRcenterEntities();
            }
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BoughtService> BoughtServices { get; set; }
        public virtual DbSet<BoughtST> BoughtSTs { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<OrderService> OrderServices { get; set; }
        public virtual DbSet<OrderST> OrderSTs { get; set; }
        public virtual DbSet<Raspisanie> Raspisanies { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<SeasonTicket> SeasonTickets { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Timetable> Timetables { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Week> Weeks { get; set; }
    }
}
