//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRcenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderST
    {
        public int OrderSTID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> SeasonTicketID { get; set; }
        public Nullable<System.DateTime> DateOrder { get; set; }
        public string Status { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual SeasonTicket SeasonTicket { get; set; }
    }
}
