//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRcenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Raspisanie
    {
        public byte WeekID { get; set; }
        public System.TimeSpan Time { get; set; }
        public int SeasonTicketID { get; set; }
    
        public virtual SeasonTicket SeasonTicket { get; set; }
        public virtual Week Week { get; set; }
    }
}
