//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRcenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timetable
    {
        public int TimetableID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public int BoughtSTID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual BoughtST BoughtST { get; set; }
        public virtual Client Client { get; set; }
        public virtual User User { get; set; }
    }
}
