//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRcenter.Models
{
    using System;
    using System.Collections.Generic;
    using System.IO;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.BoughtServices = new HashSet<BoughtService>();
            this.Timetables = new HashSet<Timetable>();
        }
        public string GetPhoto
        {
            get
            {
                if (U_photo is null)
                    return null;
                return Directory.GetCurrentDirectory() + @"\Images\" + U_photo.Trim();
            }
        }

        public int UserID { get; set; }
        public string U_name { get; set; }
        public string U_phone { get; set; }
        public string U_email { get; set; }
        public System.DateTime U_bitrhday { get; set; }
        public string U_ip { get; set; }
        public string U_login { get; set; }
        public string U_password { get; set; }
        public string U_photo { get; set; }
        public Nullable<int> RoleID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BoughtService> BoughtServices { get; set; }
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Timetable> Timetables { get; set; }
    }
}
